!function(e){var n={};function t(o){if(n[o])return n[o].exports;var r=n[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,t),r.l=!0,r.exports}t.m=e,t.c=n,t.d=function(e,n,o){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:o})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,n){if(1&n&&(e=t(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(t.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var r in e)t.d(o,r,function(n){return e[n]}.bind(null,r));return o},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},t.p="",t(t.s=0)}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no static exports found */function(module,exports){eval("\n\n//# sourceURL=webpack:///./src/js/main.js?")},"./src/js/modal.js":
/*!*************************!*\
  !*** ./src/js/modal.js ***!
  \*************************/
/*! no static exports found */function(module,exports){eval("var btns = document.querySelectorAll('.btn');\nvar modalsOverlay = document.querySelector('.modal-overlay');\nvar modals = document.querySelectorAll('.modal');\nbtns.forEach(function (el) {\n  el.addEventListener('click', function (e) {\n    var path = e.currentTarget.getAttribute('data-path');\n    modals.forEach(function (el) {\n      el.classList.remove('modal--visibality');\n    });\n    document.querySelector(\"[data-target=\\\"\".concat(path, \"\\\"]\")).classList.add('modal--visibality');\n    modalsOverlay.classList.add('modal-overlay--visibality');\n  });\n});\nmodalsOverlay.addEventListener('click', function (e) {\n  if (e.target == modalsOverlay) {\n    modalsOverlay.classList.remove('modal-overlay--visibality');\n    modals.forEach(function (el) {\n      el.classList.remove('modal--visibality');\n    });\n  }\n});\nvar closeModal = document.querySelectorAll('.modal--close');\ncloseModal.forEach(function (el) {\n  el.addEventListener('click', function (e) {\n    var close = e.currentTarget.getAttribute('data-close');\n\n    if (close == 'close') {\n      modalsOverlay.classList.remove('modal-overlay--visibality');\n      modals.forEach(function (el) {\n        el.classList.remove('modal--visibality');\n      });\n    }\n  });\n});\n\n//# sourceURL=webpack:///./src/js/modal.js?")},0:
/*!************************************************!*\
  !*** multi ./src/js/main.js ./src/js/modal.js ***!
  \************************************************/
/*! no static exports found */function(module,exports,__webpack_require__){eval('__webpack_require__(/*! I:\\GitHub News\\websites-portfolio\\antools\\src\\js\\main.js */"./src/js/main.js");\nmodule.exports = __webpack_require__(/*! I:\\GitHub News\\websites-portfolio\\antools\\src\\js\\modal.js */"./src/js/modal.js");\n\n\n//# sourceURL=webpack:///multi_./src/js/main.js_./src/js/modal.js?')}});
//# sourceMappingURL=main.js.map
